name: Linux GCC

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  
  serial-no-hdf:
    if: github.event.pull_request.draft == false
    name: GNU@10.0 C++14 serial without HDF5
    runs-on: ubuntu-latest
    env: 
      CHOMBO_HOME: ${{github.workspace}}/Chombo-3.3/lib
      DISCHARGE_HOME: ${{github.workspace}}/chombo-discharge

    steps:
      - name: Checkout Chombo
        uses: actions/checkout@master
        with:
          repository: chombo-discharge/Chombo-3.3
          path: Chombo-3.3

      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          repository: chombo-discharge/chombo-discharge
          path: chombo-discharge

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

      - name: Setup compilers
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

      - name: Copy makefile
        run: |
          cp $DISCHARGE_HOME/Local/CI/Make.defs.linux-gcc $CHOMBO_HOME/mk/Make.defs.local          

      - name: Build Chombo (2D)
        run: |
          make -s -j2 DIM=2 lib
        working-directory: ${{ env.CHOMBO_HOME }}

      - name: Build Chombo (3D)
        run: |
          make -s -j2 DIM=3 lib
        working-directory: ${{ env.CHOMBO_HOME }}

  serial-hdf:
    if: github.event.pull_request.draft == false    
    name: GNU@10.0 C++14 serial with HDF5    
    runs-on: ubuntu-latest
    env: 
      CHOMBO_HOME: ${{github.workspace}}/Chombo-3.3/lib
      DISCHARGE_HOME: ${{github.workspace}}/chombo-discharge

    steps:
      - name: Checkout Chombo
        uses: actions/checkout@master
        with:
          repository: chombo-discharge/Chombo-3.3
          path: Chombo-3.3

      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          repository: chombo-discharge/chombo-discharge
          path: chombo-discharge

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

      - name: Setup compilers
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

      - name: Copy makefile
        run: |
          cp $DISCHARGE_HOME/Local/CI/Make.defs.HDF5.linux-gcc $CHOMBO_HOME/mk/Make.defs.local
          
      - name: Build Chombo (2D)
        run: |
          make -s -j2 DIM=2 lib
        working-directory: ${{ env.CHOMBO_HOME }}

      - name: Build Chombo (3D)
        run: |
          make -s -j2 DIM=3 lib
        working-directory: ${{ env.CHOMBO_HOME }}        
        
  mpi-no-hdf5:
    if: github.event.pull_request.draft == false        
    name: GNU@10.0 C++14 OpenMPI without HDF5    
    runs-on: ubuntu-latest
    env: 
      CHOMBO_HOME: ${{github.workspace}}/Chombo-3.3/lib
      DISCHARGE_HOME: ${{github.workspace}}/chombo-discharge

    steps:
      - name: Checkout Chombo
        uses: actions/checkout@master
        with:
          repository: chombo-discharge/Chombo-3.3
          path: Chombo-3.3

      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          repository: chombo-discharge/chombo-discharge
          path: chombo-discharge

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

      - name: Setup compilers
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

      - name: Copy makefile
        run: |
          cp $DISCHARGE_HOME/Local/CI/Make.defs.MPI.linux-gcc $CHOMBO_HOME/mk/Make.defs.local
          
      - name: Build Chombo (2D)
        run: |
          make -s -j2 DIM=2 DEBUG=TRUE OPT=TRUE lib
        working-directory: ${{ env.CHOMBO_HOME }}

      - name: Build Chombo (3D)
        run: |
          make -s -j2 DIM=3 DEBUG=TRUE OPT=TRUE lib
        working-directory: ${{ env.CHOMBO_HOME }}

  mpi-hdf5:
    if: github.event.pull_request.draft == false        
    name: GNU@10.0 C++14 OpenMPI with HDF5        
    runs-on: ubuntu-latest
    env: 
      CHOMBO_HOME: ${{github.workspace}}/Chombo-3.3/lib
      DISCHARGE_HOME: ${{github.workspace}}/chombo-discharge

    steps:
      - name: Checkout Chombo
        uses: actions/checkout@master
        with:
          repository: chombo-discharge/Chombo-3.3
          path: Chombo-3.3

      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          repository: chombo-discharge/chombo-discharge
          path: chombo-discharge

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

      - name: Setup compilers
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

      - name: Copy makefile
        run: |
          cp $DISCHARGE_HOME/Local/CI/Make.defs.MPI.HDF5.linux-gcc $CHOMBO_HOME/mk/Make.defs.local
          
      - name: Build Chombo (2D)
        run: |
          make -s -j2 DIM=2 DEBUG=TRUE OPT=TRUE lib
        working-directory: ${{ env.CHOMBO_HOME }}

      - name: Build Chombo (3D)
        run: |
          make -s -j2 DIM=3 DEBUG=TRUE OPT=TRUE lib
        working-directory: ${{ env.CHOMBO_HOME }}                
