name: Linux GCC

on:
  pull_request:
    types: [push, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc    
  cancel-in-progress: true

jobs:
  serial-no-hdf:
    if: github.event.pull_request.draft == false  
    name: GNU@10.0 C++14 serial without HDF5
    runs-on: ubuntu-latest
    timeout-minutes: 300
    
    env: 
      DISCHARGE_HOME: ${{github.workspace}}
      CHOMBO_HOME: ${{github.workspace}}/Submodules/Chombo-3.3/lib

    steps:
      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

      - name: Setup compilers
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

      - name: Copy makefile
        run: |
          cp $DISCHARGE_HOME/Local/GitHub/Make.defs.linux-gcc $CHOMBO_HOME/mk/Make.defs.local

      - name: Build Chombo (2D)
        run: |
          make -s -j2 DIM=2 chombo

      - name: Build chombo-discharge/source (2D)
        run: |
          make -s -j2 DIM=2 discharge-source

      - name: Build chombo-discharge/geometries (2D)
        run: |
          make -s -j2 DIM=2 discharge-geometries

      - name: Build chombo-discharge/physics (2D)
        run: |
          make -s -j2 DIM=2 discharge-physics

      - name: Build Chombo (3D)
        run: |
          make -s -j2 DIM=3 chombo          

      - name: Build chombo-discharge/source (3D)
        run: |
          make -s -j2 DIM=3 discharge-source

      - name: Build chombo-discharge/geometries (3D)
        run: |
          make -s -j2 DIM=3 discharge-geometries

      - name: Build chombo-discharge/physics (3D)
        run: |
          make -s -j2 DIM=3 discharge-physics

      - name: Compile and run tests
        working-directory: ${{ env.DISCHARGE_HOME}}/Tests        
        run: |
          python3 tests.py --compile --benchmark --silent -cores 2

  serial-hdf:
    if: github.event.pull_request.draft == false    
    name: GNU@10.0 C++14 serial with HDF5    
    runs-on: ubuntu-latest
    timeout-minutes: 300
    
    env:
      DISCHARGE_HOME: ${{github.workspace}}
      CHOMBO_HOME: ${{github.workspace}}/Submodules/Chombo-3.3/lib

    steps:
      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

      - name: Setup compilers
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

      - name: Copy makefile
        run: |
          cp $DISCHARGE_HOME/Local/GitHub/Make.defs.HDF5.linux-gcc $CHOMBO_HOME/mk/Make.defs.local

      - name: Build Chombo (2D)
        run: |
          make -s -j2 DIM=2 chombo

      - name: Build chombo-discharge/source (2D)
        run: |
          make -s -j2 DIM=2 discharge-source

      - name: Build chombo-discharge/geometries (2D)
        run: |
          make -s -j2 DIM=2 discharge-geometries

      - name: Build chombo-discharge/physics (2D)
        run: |
          make -s -j2 DIM=2 discharge-physics

      - name: Build Chombo (3D)
        run: |
          make -s -j2 DIM=3 chombo

      - name: Build chombo-discharge/source (3D)
        run: |
          make -s -j2 DIM=3 discharge-source

      - name: Build chombo-discharge/geometries (3D)
        run: |
          make -s -j2 DIM=3 discharge-geometries

      - name: Build chombo-discharge/physics (3D)
        run: |
          make -s -j2 DIM=3 discharge-physics

      - name: Compile and run tests
        working-directory: ${{ env.DISCHARGE_HOME}}/Tests        
        run: |
          python3 tests.py --compile --benchmark --silent -cores 2
        
  mpi-no-hdf5:
    if: github.event.pull_request.draft == false        
    name: GNU@10.0 C++14 OpenMPI without HDF5    
    runs-on: ubuntu-latest
    timeout-minutes: 300
    
    env: 
      DISCHARGE_HOME: ${{github.workspace}}
      CHOMBO_HOME: ${{github.workspace}}/Submodules/Chombo-3.3/lib

    steps:
      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

      - name: Setup compilers
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

      - name: Copy makefile
        run: |
          cp $DISCHARGE_HOME/Local/GitHub/Make.defs.MPI.linux-gcc $CHOMBO_HOME/mk/Make.defs.local

      - name: Build Chombo (2D)
        run: |
          make -s -j2 DIM=2 chombo

      - name: Build chombo-discharge/source (2D)
        run: |
          make -s -j2 DIM=2 discharge-source

      - name: Build chombo-discharge/geometries (2D)
        run: |
          make -s -j2 DIM=2 discharge-geometries

      - name: Build chombo-discharge/physics (2D)
        run: |
          make -s -j2 DIM=2 discharge-physics

      - name: Build Chombo (3D)
        run: |
          make -s -j2 DIM=3 chombo

      - name: Build chombo-discharge/source (3D)
        run: |
          make -s -j2 DIM=3 discharge-source

      - name: Build chombo-discharge/geometries (3D)
        run: |
          make -s -j2 DIM=3 discharge-geometries

      - name: Build chombo-discharge/physics (3D)
        run: |
          make -s -j2 DIM=3 discharge-physics

      - name: Compile and run tests
        working-directory: ${{ env.DISCHARGE_HOME}}/Tests        
        run: |
          python3 tests.py --compile --benchmark --silent -cores 2 --parallel   

  mpi-hdf5:
    if: github.event.pull_request.draft == false        
    name: GNU@10.0 C++14 OpenMPI with HDF5        
    runs-on: ubuntu-latest
    timeout-minutes: 300
    
    env: 
      DISCHARGE_HOME: ${{github.workspace}}
      CHOMBO_HOME: ${{github.workspace}}/Submodules/Chombo-3.3/lib

    steps:
      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

      - name: Setup compilers
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

      - name: Copy makefile
        run: |
          cp $DISCHARGE_HOME/Local/GitHub/Make.defs.MPI.HDF5.linux-gcc $CHOMBO_HOME/mk/Make.defs.local

      - name: Build Chombo (2D)
        run: |
          make -s -j2 DIM=2 chombo

      - name: Build chombo-discharge/source (2D)
        run: |
          make -s -j2 DIM=2 discharge-source

      - name: Build chombo-discharge/geometries (2D)
        run: |
          make -s -j2 DIM=2 discharge-geometries

      - name: Build chombo-discharge/physics (2D)
        run: |
          make -s -j2 DIM=2 discharge-physics

      - name: Build Chombo (3D)
        run: |
          make -s -j2 DIM=3 chombo

      - name: Build chombo-discharge/source (3D)
        run: |
          make -s -j2 DIM=3 discharge-source

      - name: Build chombo-discharge/geometries (3D)
        run: |
          make -s -j2 DIM=3 discharge-geometries

      - name: Build chombo-discharge/physics (3D)
        run: |
          make -s -j2 DIM=3 discharge-physics

      - name: Compile and run tests
        working-directory: ${{ env.DISCHARGE_HOME}}/Tests        
        run: |
          python3 tests.py --compile --benchmark --silent -cores 2 --parallel
